### ISSUE TITLE
Cannot reproduce the result.

### ISSUE THREAD

**Issue by Wallace-222** [raspberryice/ala-gcn#4]
First of all, the naming of the methods between the code and the paper is not consistent. Could you tell me whether "Ala" is "Ada"?

Second, could you provide a single command that can reproduce the results in paper's table? For example, "python train.py --percentage 0.01" cannot obtain the result shown in the table3.

**Comment by raspberryice** [comment]
Hi Wallace, 
The naming in the code starts with `Ada`. We initially tried to name our model "Adaptive" but then we realize the name was taken. 
As for the command, I will double check with the first author and update that to the `README` file. Sorry for the wait.

**Comment by Ruijia-Xu** [comment]
Thank you. It is nice of you.

**Comment by Wallace-222** [comment]
Thank you. It is nice of you.

**Comment by raspberryice** [comment]
Hi Wallace, please see the updated `README` file.

**Comment by Wallace-222** [comment]
Actually, according to your given command, the accuracies are still 4-5 points lower than that in your paper.

Besides, it seems there is a bug in your code (Line 16 in model.py). It will not send the graph to the gpu. It have to be "self.graph = self.graph.to...". This is the only change I made. Otherwise, it cannot run at all.

But the accuracies are still very low compared with your paper. Do you have any ideas. Thanks.

**Comment by raspberryice** [comment]
Hi Wallace,
To confirm the bug you reported, I ran the code just now and it seems to be ok on my side. I suspect it is due to an API change in `dgl`. The version on my side is 0.4.1.

As for reproduction,
I ran the command for AlaGCN on Cora 5% with two different seeds 2020 and 0 and got 83.1 and 83.8 accuracy respectively. 

Can you point out which experiment in particular that you are trying to reproduce?
